log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "msgconsumer"
bot:
  token: "bot token"
  payment_token: "payment token"
button_redis:
  addr: "redis:6379"
  pwd: "redis123"
  db: 1
  ttl: 1h
kafka:
  brokers:
    - localhost:9092
  topic: "debezium.public.outbox_messages"
  consumer_group: "group_outbox_messages"